/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables.records;


import com.st1580.diploma.db.tables.AlphaToBeta;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlphaToBetaRecord extends UpdatableRecordImpl<AlphaToBetaRecord> implements Record8<Long, Long, String, Boolean, String, String, Boolean, Long> {

    private static final long serialVersionUID = 2059047437;

    /**
     * Setter for <code>public.alpha_to_beta.alpha_id</code>.
     */
    public void setAlphaId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.alpha_id</code>.
     */
    public Long getAlphaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.alpha_to_beta.beta_id</code>.
     */
    public void setBetaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.beta_id</code>.
     */
    public Long getBetaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.alpha_to_beta.hash</code>.
     */
    public void setHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.hash</code>.
     */
    public String getHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.alpha_to_beta.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.alpha_to_beta.is_active_alpha</code>.
     */
    public void setIsActiveAlpha(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.is_active_alpha</code>.
     */
    public String getIsActiveAlpha() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.alpha_to_beta.is_active_beta</code>.
     */
    public void setIsActiveBeta(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.is_active_beta</code>.
     */
    public String getIsActiveBeta() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.alpha_to_beta.can_use</code>.
     */
    public void setCanUse(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.can_use</code>.
     */
    public Boolean getCanUse() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.alpha_to_beta.created_ts</code>.
     */
    public void setCreatedTs(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.created_ts</code>.
     */
    public Long getCreatedTs() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Long, Long, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, String, Boolean, String, String, Boolean, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, String, Boolean, String, String, Boolean, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AlphaToBeta.ALPHA_TO_BETA.ALPHA_ID;
    }

    @Override
    public Field<Long> field2() {
        return AlphaToBeta.ALPHA_TO_BETA.BETA_ID;
    }

    @Override
    public Field<String> field3() {
        return AlphaToBeta.ALPHA_TO_BETA.HASH;
    }

    @Override
    public Field<Boolean> field4() {
        return AlphaToBeta.ALPHA_TO_BETA.IS_ACTIVE;
    }

    @Override
    public Field<String> field5() {
        return AlphaToBeta.ALPHA_TO_BETA.IS_ACTIVE_ALPHA;
    }

    @Override
    public Field<String> field6() {
        return AlphaToBeta.ALPHA_TO_BETA.IS_ACTIVE_BETA;
    }

    @Override
    public Field<Boolean> field7() {
        return AlphaToBeta.ALPHA_TO_BETA.CAN_USE;
    }

    @Override
    public Field<Long> field8() {
        return AlphaToBeta.ALPHA_TO_BETA.CREATED_TS;
    }

    @Override
    public Long component1() {
        return getAlphaId();
    }

    @Override
    public Long component2() {
        return getBetaId();
    }

    @Override
    public String component3() {
        return getHash();
    }

    @Override
    public Boolean component4() {
        return getIsActive();
    }

    @Override
    public String component5() {
        return getIsActiveAlpha();
    }

    @Override
    public String component6() {
        return getIsActiveBeta();
    }

    @Override
    public Boolean component7() {
        return getCanUse();
    }

    @Override
    public Long component8() {
        return getCreatedTs();
    }

    @Override
    public Long value1() {
        return getAlphaId();
    }

    @Override
    public Long value2() {
        return getBetaId();
    }

    @Override
    public String value3() {
        return getHash();
    }

    @Override
    public Boolean value4() {
        return getIsActive();
    }

    @Override
    public String value5() {
        return getIsActiveAlpha();
    }

    @Override
    public String value6() {
        return getIsActiveBeta();
    }

    @Override
    public Boolean value7() {
        return getCanUse();
    }

    @Override
    public Long value8() {
        return getCreatedTs();
    }

    @Override
    public AlphaToBetaRecord value1(Long value) {
        setAlphaId(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord value2(Long value) {
        setBetaId(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord value3(String value) {
        setHash(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord value4(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord value5(String value) {
        setIsActiveAlpha(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord value6(String value) {
        setIsActiveBeta(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord value7(Boolean value) {
        setCanUse(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord value8(Long value) {
        setCreatedTs(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord values(Long value1, Long value2, String value3, Boolean value4, String value5, String value6, Boolean value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlphaToBetaRecord
     */
    public AlphaToBetaRecord() {
        super(AlphaToBeta.ALPHA_TO_BETA);
    }

    /**
     * Create a detached, initialised AlphaToBetaRecord
     */
    public AlphaToBetaRecord(Long alphaId, Long betaId, String hash, Boolean isActive, String isActiveAlpha, String isActiveBeta, Boolean canUse, Long createdTs) {
        super(AlphaToBeta.ALPHA_TO_BETA);

        set(0, alphaId);
        set(1, betaId);
        set(2, hash);
        set(3, isActive);
        set(4, isActiveAlpha);
        set(5, isActiveBeta);
        set(6, canUse);
        set(7, createdTs);
    }
}
