/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables.records;


import com.st1580.diploma.db.tables.AlphaToBeta;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlphaToBetaRecord extends UpdatableRecordImpl<AlphaToBetaRecord> implements Record3<Long, Long, String> {

    private static final long serialVersionUID = -1368732093;

    /**
     * Setter for <code>public.alpha_to_beta.alpha_id</code>.
     */
    public void setAlphaId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.alpha_id</code>.
     */
    public Long getAlphaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.alpha_to_beta.beta_id</code>.
     */
    public void setBetaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.beta_id</code>.
     */
    public Long getBetaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.alpha_to_beta.property_1</code>.
     */
    public void setProperty_1(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.alpha_to_beta.property_1</code>.
     */
    public String getProperty_1() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AlphaToBeta.ALPHA_TO_BETA.ALPHA_ID;
    }

    @Override
    public Field<Long> field2() {
        return AlphaToBeta.ALPHA_TO_BETA.BETA_ID;
    }

    @Override
    public Field<String> field3() {
        return AlphaToBeta.ALPHA_TO_BETA.PROPERTY_1;
    }

    @Override
    public Long component1() {
        return getAlphaId();
    }

    @Override
    public Long component2() {
        return getBetaId();
    }

    @Override
    public String component3() {
        return getProperty_1();
    }

    @Override
    public Long value1() {
        return getAlphaId();
    }

    @Override
    public Long value2() {
        return getBetaId();
    }

    @Override
    public String value3() {
        return getProperty_1();
    }

    @Override
    public AlphaToBetaRecord value1(Long value) {
        setAlphaId(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord value2(Long value) {
        setBetaId(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord value3(String value) {
        setProperty_1(value);
        return this;
    }

    @Override
    public AlphaToBetaRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlphaToBetaRecord
     */
    public AlphaToBetaRecord() {
        super(AlphaToBeta.ALPHA_TO_BETA);
    }

    /**
     * Create a detached, initialised AlphaToBetaRecord
     */
    public AlphaToBetaRecord(Long alphaId, Long betaId, String property_1) {
        super(AlphaToBeta.ALPHA_TO_BETA);

        set(0, alphaId);
        set(1, betaId);
        set(2, property_1);
    }
}
