/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables.records;


import com.st1580.diploma.db.tables.Alpha;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlphaRecord extends UpdatableRecordImpl<AlphaRecord> implements Record5<Long, String, String, Long, Long> {

    private static final long serialVersionUID = -205541609;

    /**
     * Setter for <code>public.alpha.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.alpha.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.alpha.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.alpha.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.alpha.property_1</code>.
     */
    public void setProperty_1(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.alpha.property_1</code>.
     */
    public String getProperty_1() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.alpha.property_2</code>.
     */
    public void setProperty_2(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.alpha.property_2</code>.
     */
    public Long getProperty_2() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.alpha.property_3</code>.
     */
    public void setProperty_3(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.alpha.property_3</code>.
     */
    public Long getProperty_3() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Alpha.ALPHA.ID;
    }

    @Override
    public Field<String> field2() {
        return Alpha.ALPHA.NAME;
    }

    @Override
    public Field<String> field3() {
        return Alpha.ALPHA.PROPERTY_1;
    }

    @Override
    public Field<Long> field4() {
        return Alpha.ALPHA.PROPERTY_2;
    }

    @Override
    public Field<Long> field5() {
        return Alpha.ALPHA.PROPERTY_3;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getProperty_1();
    }

    @Override
    public Long component4() {
        return getProperty_2();
    }

    @Override
    public Long component5() {
        return getProperty_3();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getProperty_1();
    }

    @Override
    public Long value4() {
        return getProperty_2();
    }

    @Override
    public Long value5() {
        return getProperty_3();
    }

    @Override
    public AlphaRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AlphaRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AlphaRecord value3(String value) {
        setProperty_1(value);
        return this;
    }

    @Override
    public AlphaRecord value4(Long value) {
        setProperty_2(value);
        return this;
    }

    @Override
    public AlphaRecord value5(Long value) {
        setProperty_3(value);
        return this;
    }

    @Override
    public AlphaRecord values(Long value1, String value2, String value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlphaRecord
     */
    public AlphaRecord() {
        super(Alpha.ALPHA);
    }

    /**
     * Create a detached, initialised AlphaRecord
     */
    public AlphaRecord(Long id, String name, String property_1, Long property_2, Long property_3) {
        super(Alpha.ALPHA);

        set(0, id);
        set(1, name);
        set(2, property_1);
        set(3, property_2);
        set(4, property_3);
    }
}
