/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables.records;


import com.st1580.diploma.db.tables.Gamma;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GammaRecord extends UpdatableRecordImpl<GammaRecord> implements Record5<Long, String, Long, String, Boolean> {

    private static final long serialVersionUID = -72167384;

    /**
     * Setter for <code>public.gamma.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.gamma.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.gamma.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.gamma.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.gamma.property_1</code>.
     */
    public void setProperty_1(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.gamma.property_1</code>.
     */
    public Long getProperty_1() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.gamma.property_2</code>.
     */
    public void setProperty_2(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.gamma.property_2</code>.
     */
    public String getProperty_2() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.gamma.property_3</code>.
     */
    public void setProperty_3(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.gamma.property_3</code>.
     */
    public Boolean getProperty_3() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Long, String, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, Long, String, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Gamma.GAMMA.ID;
    }

    @Override
    public Field<String> field2() {
        return Gamma.GAMMA.NAME;
    }

    @Override
    public Field<Long> field3() {
        return Gamma.GAMMA.PROPERTY_1;
    }

    @Override
    public Field<String> field4() {
        return Gamma.GAMMA.PROPERTY_2;
    }

    @Override
    public Field<Boolean> field5() {
        return Gamma.GAMMA.PROPERTY_3;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getProperty_1();
    }

    @Override
    public String component4() {
        return getProperty_2();
    }

    @Override
    public Boolean component5() {
        return getProperty_3();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getProperty_1();
    }

    @Override
    public String value4() {
        return getProperty_2();
    }

    @Override
    public Boolean value5() {
        return getProperty_3();
    }

    @Override
    public GammaRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GammaRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GammaRecord value3(Long value) {
        setProperty_1(value);
        return this;
    }

    @Override
    public GammaRecord value4(String value) {
        setProperty_2(value);
        return this;
    }

    @Override
    public GammaRecord value5(Boolean value) {
        setProperty_3(value);
        return this;
    }

    @Override
    public GammaRecord values(Long value1, String value2, Long value3, String value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GammaRecord
     */
    public GammaRecord() {
        super(Gamma.GAMMA);
    }

    /**
     * Create a detached, initialised GammaRecord
     */
    public GammaRecord(Long id, String name, Long property_1, String property_2, Boolean property_3) {
        super(Gamma.GAMMA);

        set(0, id);
        set(1, name);
        set(2, property_1);
        set(3, property_2);
        set(4, property_3);
    }
}
