/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables.records;


import com.st1580.diploma.db.tables.GammaToAlpha;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GammaToAlphaRecord extends UpdatableRecordImpl<GammaToAlphaRecord> implements Record4<Long, Long, Long, String> {

    private static final long serialVersionUID = 326650481;

    /**
     * Setter for <code>public.gamma_to_alpha.gamma_id</code>.
     */
    public void setGammaId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.gamma_id</code>.
     */
    public Long getGammaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.alpha_id</code>.
     */
    public void setAlphaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.alpha_id</code>.
     */
    public Long getAlphaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.property_1</code>.
     */
    public void setProperty_1(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.property_1</code>.
     */
    public Long getProperty_1() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.property_2</code>.
     */
    public void setProperty_2(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.property_2</code>.
     */
    public String getProperty_2() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Long, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GammaToAlpha.GAMMA_TO_ALPHA.GAMMA_ID;
    }

    @Override
    public Field<Long> field2() {
        return GammaToAlpha.GAMMA_TO_ALPHA.ALPHA_ID;
    }

    @Override
    public Field<Long> field3() {
        return GammaToAlpha.GAMMA_TO_ALPHA.PROPERTY_1;
    }

    @Override
    public Field<String> field4() {
        return GammaToAlpha.GAMMA_TO_ALPHA.PROPERTY_2;
    }

    @Override
    public Long component1() {
        return getGammaId();
    }

    @Override
    public Long component2() {
        return getAlphaId();
    }

    @Override
    public Long component3() {
        return getProperty_1();
    }

    @Override
    public String component4() {
        return getProperty_2();
    }

    @Override
    public Long value1() {
        return getGammaId();
    }

    @Override
    public Long value2() {
        return getAlphaId();
    }

    @Override
    public Long value3() {
        return getProperty_1();
    }

    @Override
    public String value4() {
        return getProperty_2();
    }

    @Override
    public GammaToAlphaRecord value1(Long value) {
        setGammaId(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value2(Long value) {
        setAlphaId(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value3(Long value) {
        setProperty_1(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value4(String value) {
        setProperty_2(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord values(Long value1, Long value2, Long value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GammaToAlphaRecord
     */
    public GammaToAlphaRecord() {
        super(GammaToAlpha.GAMMA_TO_ALPHA);
    }

    /**
     * Create a detached, initialised GammaToAlphaRecord
     */
    public GammaToAlphaRecord(Long gammaId, Long alphaId, Long property_1, String property_2) {
        super(GammaToAlpha.GAMMA_TO_ALPHA);

        set(0, gammaId);
        set(1, alphaId);
        set(2, property_1);
        set(3, property_2);
    }
}
