/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables.records;


import com.st1580.diploma.db.tables.GammaToDelta;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GammaToDeltaRecord extends UpdatableRecordImpl<GammaToDeltaRecord> implements Record6<Long, Long, Boolean, String, String, Long> {

    private static final long serialVersionUID = -593855042;

    /**
     * Setter for <code>public.gamma_to_delta.gamma_id</code>.
     */
    public void setGammaId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.gamma_to_delta.gamma_id</code>.
     */
    public Long getGammaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.gamma_to_delta.delta_id</code>.
     */
    public void setDeltaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.gamma_to_delta.delta_id</code>.
     */
    public Long getDeltaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.gamma_to_delta.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.gamma_to_delta.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.gamma_to_delta.is_active_gamma</code>.
     */
    public void setIsActiveGamma(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.gamma_to_delta.is_active_gamma</code>.
     */
    public String getIsActiveGamma() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.gamma_to_delta.is_active_delta</code>.
     */
    public void setIsActiveDelta(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.gamma_to_delta.is_active_delta</code>.
     */
    public String getIsActiveDelta() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.gamma_to_delta.created_ts</code>.
     */
    public void setCreatedTs(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.gamma_to_delta.created_ts</code>.
     */
    public Long getCreatedTs() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Long, Long, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Boolean, String, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Boolean, String, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GammaToDelta.GAMMA_TO_DELTA.GAMMA_ID;
    }

    @Override
    public Field<Long> field2() {
        return GammaToDelta.GAMMA_TO_DELTA.DELTA_ID;
    }

    @Override
    public Field<Boolean> field3() {
        return GammaToDelta.GAMMA_TO_DELTA.IS_ACTIVE;
    }

    @Override
    public Field<String> field4() {
        return GammaToDelta.GAMMA_TO_DELTA.IS_ACTIVE_GAMMA;
    }

    @Override
    public Field<String> field5() {
        return GammaToDelta.GAMMA_TO_DELTA.IS_ACTIVE_DELTA;
    }

    @Override
    public Field<Long> field6() {
        return GammaToDelta.GAMMA_TO_DELTA.CREATED_TS;
    }

    @Override
    public Long component1() {
        return getGammaId();
    }

    @Override
    public Long component2() {
        return getDeltaId();
    }

    @Override
    public Boolean component3() {
        return getIsActive();
    }

    @Override
    public String component4() {
        return getIsActiveGamma();
    }

    @Override
    public String component5() {
        return getIsActiveDelta();
    }

    @Override
    public Long component6() {
        return getCreatedTs();
    }

    @Override
    public Long value1() {
        return getGammaId();
    }

    @Override
    public Long value2() {
        return getDeltaId();
    }

    @Override
    public Boolean value3() {
        return getIsActive();
    }

    @Override
    public String value4() {
        return getIsActiveGamma();
    }

    @Override
    public String value5() {
        return getIsActiveDelta();
    }

    @Override
    public Long value6() {
        return getCreatedTs();
    }

    @Override
    public GammaToDeltaRecord value1(Long value) {
        setGammaId(value);
        return this;
    }

    @Override
    public GammaToDeltaRecord value2(Long value) {
        setDeltaId(value);
        return this;
    }

    @Override
    public GammaToDeltaRecord value3(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public GammaToDeltaRecord value4(String value) {
        setIsActiveGamma(value);
        return this;
    }

    @Override
    public GammaToDeltaRecord value5(String value) {
        setIsActiveDelta(value);
        return this;
    }

    @Override
    public GammaToDeltaRecord value6(Long value) {
        setCreatedTs(value);
        return this;
    }

    @Override
    public GammaToDeltaRecord values(Long value1, Long value2, Boolean value3, String value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GammaToDeltaRecord
     */
    public GammaToDeltaRecord() {
        super(GammaToDelta.GAMMA_TO_DELTA);
    }

    /**
     * Create a detached, initialised GammaToDeltaRecord
     */
    public GammaToDeltaRecord(Long gammaId, Long deltaId, Boolean isActive, String isActiveGamma, String isActiveDelta, Long createdTs) {
        super(GammaToDelta.GAMMA_TO_DELTA);

        set(0, gammaId);
        set(1, deltaId);
        set(2, isActive);
        set(3, isActiveGamma);
        set(4, isActiveDelta);
        set(5, createdTs);
    }
}
