/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables.records;


import com.st1580.diploma.db.tables.GammaToAlpha;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GammaToAlphaRecord extends UpdatableRecordImpl<GammaToAlphaRecord> implements Record7<Long, Long, Long, Boolean, String, String, Long> {

    private static final long serialVersionUID = -776292601;

    /**
     * Setter for <code>public.gamma_to_alpha.gamma_id</code>.
     */
    public void setGammaId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.gamma_id</code>.
     */
    public Long getGammaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.alpha_id</code>.
     */
    public void setAlphaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.alpha_id</code>.
     */
    public Long getAlphaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.weight</code>.
     */
    public void setWeight(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.weight</code>.
     */
    public Long getWeight() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.is_active_gamma</code>.
     */
    public void setIsActiveGamma(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.is_active_gamma</code>.
     */
    public String getIsActiveGamma() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.is_active_alpha</code>.
     */
    public void setIsActiveAlpha(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.is_active_alpha</code>.
     */
    public String getIsActiveAlpha() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.created_ts</code>.
     */
    public void setCreatedTs(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.created_ts</code>.
     */
    public Long getCreatedTs() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Long, Long, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Boolean, String, String, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Boolean, String, String, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GammaToAlpha.GAMMA_TO_ALPHA.GAMMA_ID;
    }

    @Override
    public Field<Long> field2() {
        return GammaToAlpha.GAMMA_TO_ALPHA.ALPHA_ID;
    }

    @Override
    public Field<Long> field3() {
        return GammaToAlpha.GAMMA_TO_ALPHA.WEIGHT;
    }

    @Override
    public Field<Boolean> field4() {
        return GammaToAlpha.GAMMA_TO_ALPHA.IS_ACTIVE;
    }

    @Override
    public Field<String> field5() {
        return GammaToAlpha.GAMMA_TO_ALPHA.IS_ACTIVE_GAMMA;
    }

    @Override
    public Field<String> field6() {
        return GammaToAlpha.GAMMA_TO_ALPHA.IS_ACTIVE_ALPHA;
    }

    @Override
    public Field<Long> field7() {
        return GammaToAlpha.GAMMA_TO_ALPHA.CREATED_TS;
    }

    @Override
    public Long component1() {
        return getGammaId();
    }

    @Override
    public Long component2() {
        return getAlphaId();
    }

    @Override
    public Long component3() {
        return getWeight();
    }

    @Override
    public Boolean component4() {
        return getIsActive();
    }

    @Override
    public String component5() {
        return getIsActiveGamma();
    }

    @Override
    public String component6() {
        return getIsActiveAlpha();
    }

    @Override
    public Long component7() {
        return getCreatedTs();
    }

    @Override
    public Long value1() {
        return getGammaId();
    }

    @Override
    public Long value2() {
        return getAlphaId();
    }

    @Override
    public Long value3() {
        return getWeight();
    }

    @Override
    public Boolean value4() {
        return getIsActive();
    }

    @Override
    public String value5() {
        return getIsActiveGamma();
    }

    @Override
    public String value6() {
        return getIsActiveAlpha();
    }

    @Override
    public Long value7() {
        return getCreatedTs();
    }

    @Override
    public GammaToAlphaRecord value1(Long value) {
        setGammaId(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value2(Long value) {
        setAlphaId(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value3(Long value) {
        setWeight(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value4(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value5(String value) {
        setIsActiveGamma(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value6(String value) {
        setIsActiveAlpha(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value7(Long value) {
        setCreatedTs(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord values(Long value1, Long value2, Long value3, Boolean value4, String value5, String value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GammaToAlphaRecord
     */
    public GammaToAlphaRecord() {
        super(GammaToAlpha.GAMMA_TO_ALPHA);
    }

    /**
     * Create a detached, initialised GammaToAlphaRecord
     */
    public GammaToAlphaRecord(Long gammaId, Long alphaId, Long weight, Boolean isActive, String isActiveGamma, String isActiveAlpha, Long createdTs) {
        super(GammaToAlpha.GAMMA_TO_ALPHA);

        set(0, gammaId);
        set(1, alphaId);
        set(2, weight);
        set(3, isActive);
        set(4, isActiveGamma);
        set(5, isActiveAlpha);
        set(6, createdTs);
    }
}
