/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables.records;


import com.st1580.diploma.db.tables.GammaToAlpha;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GammaToAlphaRecord extends UpdatableRecordImpl<GammaToAlphaRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1965568335;

    /**
     * Setter for <code>public.gamma_to_alpha.gamma_id</code>.
     */
    public void setGammaId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.gamma_id</code>.
     */
    public Long getGammaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.gamma_to_alpha.alpha_id</code>.
     */
    public void setAlphaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.gamma_to_alpha.alpha_id</code>.
     */
    public Long getAlphaId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GammaToAlpha.GAMMA_TO_ALPHA.GAMMA_ID;
    }

    @Override
    public Field<Long> field2() {
        return GammaToAlpha.GAMMA_TO_ALPHA.ALPHA_ID;
    }

    @Override
    public Long component1() {
        return getGammaId();
    }

    @Override
    public Long component2() {
        return getAlphaId();
    }

    @Override
    public Long value1() {
        return getGammaId();
    }

    @Override
    public Long value2() {
        return getAlphaId();
    }

    @Override
    public GammaToAlphaRecord value1(Long value) {
        setGammaId(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord value2(Long value) {
        setAlphaId(value);
        return this;
    }

    @Override
    public GammaToAlphaRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GammaToAlphaRecord
     */
    public GammaToAlphaRecord() {
        super(GammaToAlpha.GAMMA_TO_ALPHA);
    }

    /**
     * Create a detached, initialised GammaToAlphaRecord
     */
    public GammaToAlphaRecord(Long gammaId, Long alphaId) {
        super(GammaToAlpha.GAMMA_TO_ALPHA);

        set(0, gammaId);
        set(1, alphaId);
    }
}
