/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables;


import com.st1580.diploma.db.Indexes;
import com.st1580.diploma.db.Keys;
import com.st1580.diploma.db.Public;
import com.st1580.diploma.db.tables.records.GammaRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gamma extends TableImpl<GammaRecord> {

    private static final long serialVersionUID = 2036244317;

    /**
     * The reference instance of <code>public.gamma</code>
     */
    public static final Gamma GAMMA = new Gamma();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GammaRecord> getRecordType() {
        return GammaRecord.class;
    }

    /**
     * The column <code>public.gamma.id</code>.
     */
    public final TableField<GammaRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.gamma.is_master</code>.
     */
    public final TableField<GammaRecord, Boolean> IS_MASTER = createField(DSL.name("is_master"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.gamma.active_status</code>.
     */
    public final TableField<GammaRecord, String> ACTIVE_STATUS = createField(DSL.name("active_status"), org.jooq.impl.SQLDataType.VARCHAR(24).nullable(false), this, "");

    /**
     * The column <code>public.gamma.created_ts</code>.
     */
    public final TableField<GammaRecord, Long> CREATED_TS = createField(DSL.name("created_ts"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.gamma</code> table reference
     */
    public Gamma() {
        this(DSL.name("gamma"), null);
    }

    /**
     * Create an aliased <code>public.gamma</code> table reference
     */
    public Gamma(String alias) {
        this(DSL.name(alias), GAMMA);
    }

    /**
     * Create an aliased <code>public.gamma</code> table reference
     */
    public Gamma(Name alias) {
        this(alias, GAMMA);
    }

    private Gamma(Name alias, Table<GammaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Gamma(Name alias, Table<GammaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Gamma(Table<O> child, ForeignKey<O, GammaRecord> key) {
        super(child, key, GAMMA);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GAMMA_ACTIVE__INDEX);
    }

    @Override
    public UniqueKey<GammaRecord> getPrimaryKey() {
        return Keys.GAMMA__PKEY;
    }

    @Override
    public List<UniqueKey<GammaRecord>> getKeys() {
        return Arrays.<UniqueKey<GammaRecord>>asList(Keys.GAMMA__PKEY);
    }

    @Override
    public Gamma as(String alias) {
        return new Gamma(DSL.name(alias), this);
    }

    @Override
    public Gamma as(Name alias) {
        return new Gamma(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gamma rename(String name) {
        return new Gamma(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gamma rename(Name name) {
        return new Gamma(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Boolean, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
