/*
 * This file is generated by jOOQ.
 */
package db.tables;


import db.Keys;
import db.Public;
import db.tables.records.DeltaRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Delta extends TableImpl<DeltaRecord> {

    private static final long serialVersionUID = 1628280372;

    /**
     * The reference instance of <code>public.delta</code>
     */
    public static final Delta DELTA = new Delta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeltaRecord> getRecordType() {
        return DeltaRecord.class;
    }

    /**
     * The column <code>public.delta.id</code>.
     */
    public final TableField<DeltaRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.delta.name</code>.
     */
    public final TableField<DeltaRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.field("'delta-entity'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.delta</code> table reference
     */
    public Delta() {
        this(DSL.name("delta"), null);
    }

    /**
     * Create an aliased <code>public.delta</code> table reference
     */
    public Delta(String alias) {
        this(DSL.name(alias), DELTA);
    }

    /**
     * Create an aliased <code>public.delta</code> table reference
     */
    public Delta(Name alias) {
        this(alias, DELTA);
    }

    private Delta(Name alias, Table<DeltaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Delta(Name alias, Table<DeltaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Delta(Table<O> child, ForeignKey<O, DeltaRecord> key) {
        super(child, key, DELTA);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<DeltaRecord> getPrimaryKey() {
        return Keys.DELTA_PKEY;
    }

    @Override
    public List<UniqueKey<DeltaRecord>> getKeys() {
        return Arrays.<UniqueKey<DeltaRecord>>asList(Keys.DELTA_PKEY);
    }

    @Override
    public Delta as(String alias) {
        return new Delta(DSL.name(alias), this);
    }

    @Override
    public Delta as(Name alias) {
        return new Delta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Delta rename(String name) {
        return new Delta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Delta rename(Name name) {
        return new Delta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
