/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Alpha;
import db.tables.AlphaToBeta;
import db.tables.Beta;
import db.tables.Delta;
import db.tables.FlywaySchemaHistory;
import db.tables.Gamma;
import db.tables.GammaToAlpha;
import db.tables.GammaToDelta;
import db.tables.records.AlphaRecord;
import db.tables.records.AlphaToBetaRecord;
import db.tables.records.BetaRecord;
import db.tables.records.DeltaRecord;
import db.tables.records.FlywaySchemaHistoryRecord;
import db.tables.records.GammaRecord;
import db.tables.records.GammaToAlphaRecord;
import db.tables.records.GammaToDeltaRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AlphaRecord> ALPHA_PKEY = UniqueKeys0.ALPHA_PKEY;
    public static final UniqueKey<AlphaToBetaRecord> ALPHA_TO_BETA__PKEY = UniqueKeys0.ALPHA_TO_BETA__PKEY;
    public static final UniqueKey<BetaRecord> BETA_PKEY = UniqueKeys0.BETA_PKEY;
    public static final UniqueKey<DeltaRecord> DELTA_PKEY = UniqueKeys0.DELTA_PKEY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<GammaRecord> GAMMA_PKEY = UniqueKeys0.GAMMA_PKEY;
    public static final UniqueKey<GammaToAlphaRecord> GAMMA_TO_ALPHA__PKEY = UniqueKeys0.GAMMA_TO_ALPHA__PKEY;
    public static final UniqueKey<GammaToDeltaRecord> GAMMA_TO_DELTA__PKEY = UniqueKeys0.GAMMA_TO_DELTA__PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AlphaToBetaRecord, AlphaRecord> ALPHA_TO_BETA__ALPHA_TO_BETA__FKEY__ALPHA_ID = ForeignKeys0.ALPHA_TO_BETA__ALPHA_TO_BETA__FKEY__ALPHA_ID;
    public static final ForeignKey<AlphaToBetaRecord, BetaRecord> ALPHA_TO_BETA__ALPHA_TO_BETA__FKEY__BETA_ID = ForeignKeys0.ALPHA_TO_BETA__ALPHA_TO_BETA__FKEY__BETA_ID;
    public static final ForeignKey<GammaToAlphaRecord, GammaRecord> GAMMA_TO_ALPHA__GAMMA_TO_ALPHA__FKEY__GAMMA_ID = ForeignKeys0.GAMMA_TO_ALPHA__GAMMA_TO_ALPHA__FKEY__GAMMA_ID;
    public static final ForeignKey<GammaToAlphaRecord, AlphaRecord> GAMMA_TO_ALPHA__GAMMA_TO_ALPHA__FKEY__ALPHA_ID = ForeignKeys0.GAMMA_TO_ALPHA__GAMMA_TO_ALPHA__FKEY__ALPHA_ID;
    public static final ForeignKey<GammaToDeltaRecord, GammaRecord> GAMMA_TO_DELTA__GAMMA_TO_DELTA__FKEY__GAMMA_ID = ForeignKeys0.GAMMA_TO_DELTA__GAMMA_TO_DELTA__FKEY__GAMMA_ID;
    public static final ForeignKey<GammaToDeltaRecord, DeltaRecord> GAMMA_TO_DELTA__GAMMA_TO_DELTA__FKEY__DELTA_ID = ForeignKeys0.GAMMA_TO_DELTA__GAMMA_TO_DELTA__FKEY__DELTA_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AlphaRecord> ALPHA_PKEY = Internal.createUniqueKey(Alpha.ALPHA, "alpha_pkey", new TableField[] { Alpha.ALPHA.ID }, true);
        public static final UniqueKey<AlphaToBetaRecord> ALPHA_TO_BETA__PKEY = Internal.createUniqueKey(AlphaToBeta.ALPHA_TO_BETA, "alpha_to_beta__pkey", new TableField[] { AlphaToBeta.ALPHA_TO_BETA.ALPHA_ID, AlphaToBeta.ALPHA_TO_BETA.BETA_ID }, true);
        public static final UniqueKey<BetaRecord> BETA_PKEY = Internal.createUniqueKey(Beta.BETA, "beta_pkey", new TableField[] { Beta.BETA.ID }, true);
        public static final UniqueKey<DeltaRecord> DELTA_PKEY = Internal.createUniqueKey(Delta.DELTA, "delta_pkey", new TableField[] { Delta.DELTA.ID }, true);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static final UniqueKey<GammaRecord> GAMMA_PKEY = Internal.createUniqueKey(Gamma.GAMMA, "gamma_pkey", new TableField[] { Gamma.GAMMA.ID }, true);
        public static final UniqueKey<GammaToAlphaRecord> GAMMA_TO_ALPHA__PKEY = Internal.createUniqueKey(GammaToAlpha.GAMMA_TO_ALPHA, "gamma_to_alpha__pkey", new TableField[] { GammaToAlpha.GAMMA_TO_ALPHA.GAMMA_ID, GammaToAlpha.GAMMA_TO_ALPHA.ALPHA_ID }, true);
        public static final UniqueKey<GammaToDeltaRecord> GAMMA_TO_DELTA__PKEY = Internal.createUniqueKey(GammaToDelta.GAMMA_TO_DELTA, "gamma_to_delta__pkey", new TableField[] { GammaToDelta.GAMMA_TO_DELTA.GAMMA_ID, GammaToDelta.GAMMA_TO_DELTA.DELTA_ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AlphaToBetaRecord, AlphaRecord> ALPHA_TO_BETA__ALPHA_TO_BETA__FKEY__ALPHA_ID = Internal.createForeignKey(Keys.ALPHA_PKEY, AlphaToBeta.ALPHA_TO_BETA, "alpha_to_beta__fkey__Alpha_id", new TableField[] { AlphaToBeta.ALPHA_TO_BETA.ALPHA_ID }, true);
        public static final ForeignKey<AlphaToBetaRecord, BetaRecord> ALPHA_TO_BETA__ALPHA_TO_BETA__FKEY__BETA_ID = Internal.createForeignKey(Keys.BETA_PKEY, AlphaToBeta.ALPHA_TO_BETA, "alpha_to_beta__fkey__Beta_id", new TableField[] { AlphaToBeta.ALPHA_TO_BETA.BETA_ID }, true);
        public static final ForeignKey<GammaToAlphaRecord, GammaRecord> GAMMA_TO_ALPHA__GAMMA_TO_ALPHA__FKEY__GAMMA_ID = Internal.createForeignKey(Keys.GAMMA_PKEY, GammaToAlpha.GAMMA_TO_ALPHA, "gamma_to_alpha__fkey__Gamma_id", new TableField[] { GammaToAlpha.GAMMA_TO_ALPHA.GAMMA_ID }, true);
        public static final ForeignKey<GammaToAlphaRecord, AlphaRecord> GAMMA_TO_ALPHA__GAMMA_TO_ALPHA__FKEY__ALPHA_ID = Internal.createForeignKey(Keys.ALPHA_PKEY, GammaToAlpha.GAMMA_TO_ALPHA, "gamma_to_alpha__fkey__Alpha_id", new TableField[] { GammaToAlpha.GAMMA_TO_ALPHA.ALPHA_ID }, true);
        public static final ForeignKey<GammaToDeltaRecord, GammaRecord> GAMMA_TO_DELTA__GAMMA_TO_DELTA__FKEY__GAMMA_ID = Internal.createForeignKey(Keys.GAMMA_PKEY, GammaToDelta.GAMMA_TO_DELTA, "gamma_to_delta__fkey__Gamma_id", new TableField[] { GammaToDelta.GAMMA_TO_DELTA.GAMMA_ID }, true);
        public static final ForeignKey<GammaToDeltaRecord, DeltaRecord> GAMMA_TO_DELTA__GAMMA_TO_DELTA__FKEY__DELTA_ID = Internal.createForeignKey(Keys.DELTA_PKEY, GammaToDelta.GAMMA_TO_DELTA, "gamma_to_delta__fkey__Delta_id", new TableField[] { GammaToDelta.GAMMA_TO_DELTA.DELTA_ID }, true);
    }
}
