/*
 * This file is generated by jOOQ.
 */
package db.tables;


import db.Keys;
import db.Public;
import db.tables.records.AlphaRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alpha extends TableImpl<AlphaRecord> {

    private static final long serialVersionUID = 797625161;

    /**
     * The reference instance of <code>public.alpha</code>
     */
    public static final Alpha ALPHA = new Alpha();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlphaRecord> getRecordType() {
        return AlphaRecord.class;
    }

    /**
     * The column <code>public.alpha.id</code>.
     */
    public final TableField<AlphaRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.alpha.name</code>.
     */
    public final TableField<AlphaRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.field("'alpha-graphEntityDto'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.alpha</code> table reference
     */
    public Alpha() {
        this(DSL.name("alpha"), null);
    }

    /**
     * Create an aliased <code>public.alpha</code> table reference
     */
    public Alpha(String alias) {
        this(DSL.name(alias), ALPHA);
    }

    /**
     * Create an aliased <code>public.alpha</code> table reference
     */
    public Alpha(Name alias) {
        this(alias, ALPHA);
    }

    private Alpha(Name alias, Table<AlphaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Alpha(Name alias, Table<AlphaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Alpha(Table<O> child, ForeignKey<O, AlphaRecord> key) {
        super(child, key, ALPHA);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<AlphaRecord> getPrimaryKey() {
        return Keys.ALPHA_PKEY;
    }

    @Override
    public List<UniqueKey<AlphaRecord>> getKeys() {
        return Arrays.<UniqueKey<AlphaRecord>>asList(Keys.ALPHA_PKEY);
    }

    @Override
    public Alpha as(String alias) {
        return new Alpha(DSL.name(alias), this);
    }

    @Override
    public Alpha as(Name alias) {
        return new Alpha(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Alpha rename(String name) {
        return new Alpha(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Alpha rename(Name name) {
        return new Alpha(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
