/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables;


import com.st1580.diploma.db.Keys;
import com.st1580.diploma.db.Public;
import com.st1580.diploma.db.tables.records.BetaRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Beta extends TableImpl<BetaRecord> {

    private static final long serialVersionUID = 560094303;

    /**
     * The reference instance of <code>public.beta</code>
     */
    public static final Beta BETA = new Beta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BetaRecord> getRecordType() {
        return BetaRecord.class;
    }

    /**
     * The column <code>public.beta.id</code>.
     */
    public final TableField<BetaRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.beta.name</code>.
     */
    public final TableField<BetaRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.field("'beta'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.beta.property_1</code>.
     */
    public final TableField<BetaRecord, Long> PROPERTY_1 = createField(DSL.name("property_1"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.beta.property_2</code>.
     */
    public final TableField<BetaRecord, Boolean> PROPERTY_2 = createField(DSL.name("property_2"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.beta</code> table reference
     */
    public Beta() {
        this(DSL.name("beta"), null);
    }

    /**
     * Create an aliased <code>public.beta</code> table reference
     */
    public Beta(String alias) {
        this(DSL.name(alias), BETA);
    }

    /**
     * Create an aliased <code>public.beta</code> table reference
     */
    public Beta(Name alias) {
        this(alias, BETA);
    }

    private Beta(Name alias, Table<BetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Beta(Name alias, Table<BetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Beta(Table<O> child, ForeignKey<O, BetaRecord> key) {
        super(child, key, BETA);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<BetaRecord> getPrimaryKey() {
        return Keys.BETA_PKEY;
    }

    @Override
    public List<UniqueKey<BetaRecord>> getKeys() {
        return Arrays.<UniqueKey<BetaRecord>>asList(Keys.BETA_PKEY);
    }

    @Override
    public Beta as(String alias) {
        return new Beta(DSL.name(alias), this);
    }

    @Override
    public Beta as(Name alias) {
        return new Beta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Beta rename(String name) {
        return new Beta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Beta rename(Name name) {
        return new Beta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Long, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
