/*
 * This file is generated by jOOQ.
 */
package com.st1580.diploma.db.tables;


import com.st1580.diploma.db.Keys;
import com.st1580.diploma.db.Public;
import com.st1580.diploma.db.tables.records.GammaRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gamma extends TableImpl<GammaRecord> {

    private static final long serialVersionUID = -1670993339;

    /**
     * The reference instance of <code>public.gamma</code>
     */
    public static final Gamma GAMMA = new Gamma();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GammaRecord> getRecordType() {
        return GammaRecord.class;
    }

    /**
     * The column <code>public.gamma.id</code>.
     */
    public final TableField<GammaRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.gamma.name</code>.
     */
    public final TableField<GammaRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.field("'gamma'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.gamma.property_1</code>.
     */
    public final TableField<GammaRecord, Long> PROPERTY_1 = createField(DSL.name("property_1"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.gamma.property_2</code>.
     */
    public final TableField<GammaRecord, String> PROPERTY_2 = createField(DSL.name("property_2"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.field("'property 2'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.gamma.property_3</code>.
     */
    public final TableField<GammaRecord, Boolean> PROPERTY_3 = createField(DSL.name("property_3"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.gamma</code> table reference
     */
    public Gamma() {
        this(DSL.name("gamma"), null);
    }

    /**
     * Create an aliased <code>public.gamma</code> table reference
     */
    public Gamma(String alias) {
        this(DSL.name(alias), GAMMA);
    }

    /**
     * Create an aliased <code>public.gamma</code> table reference
     */
    public Gamma(Name alias) {
        this(alias, GAMMA);
    }

    private Gamma(Name alias, Table<GammaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Gamma(Name alias, Table<GammaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Gamma(Table<O> child, ForeignKey<O, GammaRecord> key) {
        super(child, key, GAMMA);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<GammaRecord> getPrimaryKey() {
        return Keys.GAMMA_PKEY;
    }

    @Override
    public List<UniqueKey<GammaRecord>> getKeys() {
        return Arrays.<UniqueKey<GammaRecord>>asList(Keys.GAMMA_PKEY);
    }

    @Override
    public Gamma as(String alias) {
        return new Gamma(DSL.name(alias), this);
    }

    @Override
    public Gamma as(Name alias) {
        return new Gamma(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gamma rename(String name) {
        return new Gamma(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gamma rename(Name name) {
        return new Gamma(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Long, String, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
