/*
 * This file is generated by jOOQ.
 */
package db.tables;


import db.Keys;
import db.Public;
import db.tables.records.GammaRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gamma extends TableImpl<GammaRecord> {

    private static final long serialVersionUID = 320216376;

    /**
     * The reference instance of <code>public.gamma</code>
     */
    public static final Gamma GAMMA = new Gamma();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GammaRecord> getRecordType() {
        return GammaRecord.class;
    }

    /**
     * The column <code>public.gamma.id</code>.
     */
    public final TableField<GammaRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.gamma.name</code>.
     */
    public final TableField<GammaRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.field("'gamma-graphEntityDto'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.gamma</code> table reference
     */
    public Gamma() {
        this(DSL.name("gamma"), null);
    }

    /**
     * Create an aliased <code>public.gamma</code> table reference
     */
    public Gamma(String alias) {
        this(DSL.name(alias), GAMMA);
    }

    /**
     * Create an aliased <code>public.gamma</code> table reference
     */
    public Gamma(Name alias) {
        this(alias, GAMMA);
    }

    private Gamma(Name alias, Table<GammaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Gamma(Name alias, Table<GammaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Gamma(Table<O> child, ForeignKey<O, GammaRecord> key) {
        super(child, key, GAMMA);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<GammaRecord> getPrimaryKey() {
        return Keys.GAMMA_PKEY;
    }

    @Override
    public List<UniqueKey<GammaRecord>> getKeys() {
        return Arrays.<UniqueKey<GammaRecord>>asList(Keys.GAMMA_PKEY);
    }

    @Override
    public Gamma as(String alias) {
        return new Gamma(DSL.name(alias), this);
    }

    @Override
    public Gamma as(Name alias) {
        return new Gamma(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gamma rename(String name) {
        return new Gamma(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gamma rename(Name name) {
        return new Gamma(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
