/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Alpha;
import db.tables.AlphaToBeta;
import db.tables.Beta;
import db.tables.Delta;
import db.tables.FlywaySchemaHistory;
import db.tables.Gamma;
import db.tables.GammaToAlpha;
import db.tables.GammaToDelta;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -845159835;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.alpha</code>.
     */
    public final Alpha ALPHA = Alpha.ALPHA;

    /**
     * The table <code>public.alpha_to_beta</code>.
     */
    public final AlphaToBeta ALPHA_TO_BETA = AlphaToBeta.ALPHA_TO_BETA;

    /**
     * The table <code>public.beta</code>.
     */
    public final Beta BETA = Beta.BETA;

    /**
     * The table <code>public.delta</code>.
     */
    public final Delta DELTA = Delta.DELTA;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.gamma</code>.
     */
    public final Gamma GAMMA = Gamma.GAMMA;

    /**
     * The table <code>public.gamma_to_alpha</code>.
     */
    public final GammaToAlpha GAMMA_TO_ALPHA = GammaToAlpha.GAMMA_TO_ALPHA;

    /**
     * The table <code>public.gamma_to_delta</code>.
     */
    public final GammaToDelta GAMMA_TO_DELTA = GammaToDelta.GAMMA_TO_DELTA;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Alpha.ALPHA,
            AlphaToBeta.ALPHA_TO_BETA,
            Beta.BETA,
            Delta.DELTA,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Gamma.GAMMA,
            GammaToAlpha.GAMMA_TO_ALPHA,
            GammaToDelta.GAMMA_TO_DELTA);
    }
}
