/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Alpha;
import db.tables.AlphaToBeta;
import db.tables.Beta;
import db.tables.Delta;
import db.tables.FlywaySchemaHistory;
import db.tables.Gamma;
import db.tables.GammaToAlpha;
import db.tables.GammaToDelta;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.alpha</code>.
     */
    public static final Alpha ALPHA = Alpha.ALPHA;

    /**
     * The table <code>public.alpha_to_beta</code>.
     */
    public static final AlphaToBeta ALPHA_TO_BETA = AlphaToBeta.ALPHA_TO_BETA;

    /**
     * The table <code>public.beta</code>.
     */
    public static final Beta BETA = Beta.BETA;

    /**
     * The table <code>public.delta</code>.
     */
    public static final Delta DELTA = Delta.DELTA;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.gamma</code>.
     */
    public static final Gamma GAMMA = Gamma.GAMMA;

    /**
     * The table <code>public.gamma_to_alpha</code>.
     */
    public static final GammaToAlpha GAMMA_TO_ALPHA = GammaToAlpha.GAMMA_TO_ALPHA;

    /**
     * The table <code>public.gamma_to_delta</code>.
     */
    public static final GammaToDelta GAMMA_TO_DELTA = GammaToDelta.GAMMA_TO_DELTA;
}
